benchmark:
  description: Caliper benchmark targeting HyperWatchdog.
  name: bench_policy_gateway
  test:
    rounds:
    - description: Caliper benchmark targeting HyperWatchdog.
      label: Policy Gateway 1724
      rateControl:
        opts:
          startingTps: 100
          transactionLoad: 40
        type: fixed-load
      txDuration: 180
      workload:
        arguments:
          chaincodeID: basic
          chunkLen: 1724
          policyId: signal_energy_policy_v1
        module: benchmarks/workloads/policy-gateway.js
    workers:
      number: 1
launcher:
  fabric:
    n_orderers: 3
    n_orgs: 2
    n_peer_per_org: 2
    starting_port: 7160
  network:
    delay: 74
    jitter: 39
    loss: 3
    throughput: 2920
